prefix = "!?"
token = "YOUR_DISCORD_BOT_TOKEN_HERE"
owner = ["OWNER_DISCORD_ID"]
shardLogChannel = ""
shardStatusLogChannel = ""
lavalinkHost = "localhost"
lavalinkPort = "2333"
lavalinkPass = "youshallnotpass"
redisHost = "127.0.0.1"
redisPort = "6379"
redisPass = "redispassword"